{/* <meta ~~~~~~>

google descriptions can be autogenerated, or taken from meta tags
    SEO = search engine optimizations*/}

const jumbledLetters = ['E','d','g','z','w']

jumbledLetters.sort((a, b) => {
    a=a.toLowerCase();
    b=b.toLowerCase();
    // these shouldn't do anything becuase it doesn't change the data, a and b moves things around
    if (a<b) {
        return -1;
    } else if (a>b) {
        return 1;
    }
    return 0;
});

console.log(jumbledLetters.join(','));
